### ISSUE TITLE
Issues with milestone class

### ISSUE THREAD

**Issue by jeffgan96** [cs2103-ay1819s2-w10-2/main#60]
1. milestone class fields are still public. should change to private and set appropriate getters and setters
2. milestone Junit test cases incomplete

**Comment by ditan96** [comment]
Teach milestone class to accept '.' in name

**Comment by dehui333** [comment]
> 1. milestone class fields are still public. should change to private and set appropriate getters and setters
> 2. milestone Junit test cases incomplete

I think Milestone fields can be public, as it is the same for the fields of the objects encapsulated inside employees(like Name). I think it is because they are already private as fields of the Employee class, so we only have getName, getEmail etc under Employee class(but no getters for Name or Email), but once we get the Name or Email objects, we can just access their fields to get the String values in them.

**Comment by dehui333** [comment]
I added the tests and also made date validation more comprehensive.
